---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  username: <%= ENV["winrm_user"] %>
  password: <%= ENV["winrm_pass"] %>
  port: <%= ENV["winrm_port"] %>

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2

suites:
  - name: default
    run_list:
      - recipe[chocolatey::default]
      - recipe[chocolatey_test::default]
