---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2
  driver_config:
    box: mwrock/Windows2012R2

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[chocolatey::default]
      - recipe[chocolatey_test::default]

    attributes:
